---
document: feedback-pipeline-buildroot
version: 1
data:
  maintainer: bakery
  view_id: view-eln
  base_buildroot:
    aarch64:
      - acl
      - alternatives
      - audit-libs
      - basesystem
      - bash
      - binutils
      - binutils-gold
      - bzip2
      - bzip2-libs
      - ca-certificates
      - coreutils
      - coreutils-common
      - cpio
      - cracklib
      - cracklib-dicts
      - crypto-policies
      - crypto-policies-scripts
      - cryptsetup-libs
      - curl
      - cyrus-sasl-lib
      - dbus
      - dbus-broker
      - dbus-common
      - device-mapper
      - device-mapper-libs
      - diffutils
      - dracut
      - dwz
      - ed
      - efi-srpm-macros
      - elfutils
      - elfutils-debuginfod-client
      - elfutils-default-yama-scope
      - elfutils-libelf
      - elfutils-libs
      - expat
      - fedora-gpg-keys
      - fedora-release
      - fedora-release-common
      - fedora-release-identity-basic
      - fedora-repos
      - fedora-repos-rawhide
      - file
      - file-libs
      - filesystem
      - findutils
      - fonts-srpm-macros
      - fpc-srpm-macros
      - fuse-libs
      - gawk
      - gawk-all-langpacks
      - gc
      - gdb-minimal
      - gdbm-libs
      - gettext
      - gettext-libs
      - ghc-srpm-macros
      - glibc
      - glibc-common
      - glibc-minimal-langpack
      - gmp
      - gnat-srpm-macros
      - gnutls
      - go-srpm-macros
      - grep
      - grub2-common
      - grub2-tools
      - grub2-tools-minimal
      - grubby
      - guile22
      - gzip
      - hwdata
      - info
      - iptables-libs
      - json-c
      - kbd
      - kbd-legacy
      - kbd-misc
      - keyutils-libs
      - kmod
      - kmod-libs
      - kpartx
      - krb5-libs
      - libacl
      - libarchive
      - libargon2
      - libattr
      - libblkid
      - libbrotli
      - libcap
      - libcap-ng
      - libcom_err
      - libcurl
      - libdb
      - libeconf
      - libfdisk
      - libffi
      - libgcc
      - libgcrypt
      - libgomp
      - libgpg-error
      - libibverbs
      - libidn2
      - libkcapi
      - libkcapi-hmaccalc
      - libmetalink
      - libmnl
      - libmount
      - libnetfilter_conntrack
      - libnfnetlink
      - libnghttp2
      - libnl3
      - libnsl2
      - libpcap
      - libpkgconf
      - libpsl
      - libpwquality
      - libseccomp
      - libselinux
      - libsemanage
      - libsepol
      - libsigsegv
      - libsmartcols
      - libssh
      - libssh-config
      - libstdc++
      - libtasn1
      - libtextstyle
      - libtirpc
      - libtool-ltdl
      - libunistring
      - libutempter
      - libuuid
      - libverto
      - libxcrypt
      - libxkbcommon
      - libxml2
      - libzstd
      - lua-libs
      - lz4-libs
      - make
      - memstrack
      - mkpasswd
      - mpfr
      - ncurses
      - ncurses-base
      - ncurses-libs
      - nettle
      - nim-srpm-macros
      - ocaml-srpm-macros
      - openblas-srpm-macros
      - openldap
      - openssl-libs
      - openssl-pkcs11
      - os-prober
      - p11-kit
      - p11-kit-trust
      - pam
      - patch
      - pciutils
      - pciutils-libs
      - pcre
      - pcre2
      - pcre2-syntax
      - perl-srpm-macros
      - pigz
      - pkgconf
      - pkgconf-m4
      - pkgconf-pkg-config
      - popt
      - procps-ng
      - publicsuffix-list-dafsa
      - python-pip-wheel
      - python-setuptools-wheel
      - python-srpm-macros
      - python-unversioned-command
      - python3
      - python3-libs
      - python3-pip
      - python3-setuptools
      - qrencode-libs
      - qt5-srpm-macros
      - rdma-core
      - readline
      - redhat-rpm-config
      - rpm
      - rpm-build
      - rpm-build-libs
      - rpm-libs
      - rust-srpm-macros
      - sed
      - setup
      - shadow-utils
      - sqlite-libs
      - systemd
      - systemd-libs
      - systemd-pam
      - systemd-rpm-macros
      - systemd-udev
      - tar
      - trousers
      - trousers-lib
      - tzdata
      - unzip
      - util-linux
      - which
      - whois-nls
      - xkeyboard-config
      - xxhash-libs
      - xz
      - xz-libs
      - zip
      - zlib
      - zstd
    ppc64le:
    s390x:
      - acl
      - alternatives
      - audit-libs
      - basesystem
      - bash
      - binutils
      - binutils-gold
      - bzip2
      - bzip2-libs
      - ca-certificates
      - coreutils
      - coreutils-common
      - cpio
      - cracklib
      - cracklib-dicts
      - crypto-policies
      - crypto-policies-scripts
      - cryptsetup-libs
      - curl
      - cyrus-sasl-lib
      - dbus
      - dbus-broker
      - dbus-common
      - device-mapper
      - device-mapper-libs
      - diffutils
      - dwz
      - ed
      - efi-srpm-macros
      - elfutils
      - elfutils-debuginfod-client
      - elfutils-default-yama-scope
      - elfutils-libelf
      - elfutils-libs
      - ethtool
      - expat
      - fedora-gpg-keys
      - fedora-release
      - fedora-release-common
      - fedora-release-identity-basic
      - fedora-repos
      - fedora-repos-rawhide
      - file
      - file-libs
      - filesystem
      - findutils
      - fonts-srpm-macros
      - fpc-srpm-macros
      - fuse-libs
      - gawk
      - gawk-all-langpacks
      - gc
      - gdb-minimal
      - gdbm-libs
      - ghc-srpm-macros
      - glib2
      - glibc
      - glibc-common
      - glibc-minimal-langpack
      - gmp
      - gnat-srpm-macros
      - gnutls
      - go-srpm-macros
      - grep
      - groff-base
      - grubby
      - guile22
      - gzip
      - hwdata
      - info
      - iptables-libs
      - json-c
      - keyutils-libs
      - kmod-libs
      - krb5-libs
      - libacl
      - libarchive
      - libargon2
      - libattr
      - libblkid
      - libbrotli
      - libcap
      - libcap-ng
      - libcom_err
      - libcurl
      - libdb
      - libeconf
      - libfdisk
      - libffi
      - libgcc
      - libgcrypt
      - libgomp
      - libgpg-error
      - libibverbs
      - libidn2
      - libmetalink
      - libmnl
      - libmount
      - libnetfilter_conntrack
      - libnfnetlink
      - libnghttp2
      - libnl3
      - libnsl2
      - libpcap
      - libpkgconf
      - libpsl
      - libpwquality
      - libseccomp
      - libselinux
      - libsemanage
      - libsepol
      - libsigsegv
      - libsmartcols
      - libssh
      - libssh-config
      - libstdc++
      - libsysfs
      - libtasn1
      - libtirpc
      - libtool-ltdl
      - libunistring
      - libutempter
      - libuuid
      - libverto
      - libxcrypt
      - libxkbcommon
      - libxml2
      - libzstd
      - lua-libs
      - lz4-libs
      - make
      - mkpasswd
      - mpfr
      - ncurses
      - ncurses-base
      - ncurses-libs
      - nettle
      - nim-srpm-macros
      - ocaml-srpm-macros
      - openblas-srpm-macros
      - openldap
      - openssl-libs
      - openssl-pkcs11
      - p11-kit
      - p11-kit-trust
      - pam
      - patch
      - pciutils
      - pciutils-libs
      - pcre
      - pcre2
      - pcre2-syntax
      - perl-AutoLoader
      - perl-B
      - perl-Carp
      - perl-Class-Struct
      - perl-Data-Dumper
      - perl-Digest
      - perl-Digest-MD5
      - perl-Encode
      - perl-English
      - perl-Errno
      - perl-Exporter
      - perl-Fcntl
      - perl-File-Basename
      - perl-File-Path
      - perl-File-Temp
      - perl-File-stat
      - perl-FileHandle
      - perl-Getopt-Long
      - perl-Getopt-Std
      - perl-HTTP-Tiny
      - perl-IO
      - perl-IO-Socket-IP
      - perl-IO-Socket-SSL
      - perl-IPC-Open3
      - perl-MIME-Base64
      - perl-Mozilla-CA
      - perl-NDBM_File
      - perl-Net-SSLeay
      - perl-POSIX
      - perl-PathTools
      - perl-Pod-Escapes
      - perl-Pod-Perldoc
      - perl-Pod-Simple
      - perl-Pod-Usage
      - perl-Scalar-List-Utils
      - perl-SelectSaver
      - perl-Socket
      - perl-Storable
      - perl-Symbol
      - perl-Term-ANSIColor
      - perl-Term-Cap
      - perl-Text-ParseWords
      - perl-Text-Tabs+Wrap
      - perl-Time-Local
      - perl-URI
      - perl-base
      - perl-constant
      - perl-if
      - perl-interpreter
      - perl-libnet
      - perl-libs
      - perl-macros
      - perl-mro
      - perl-overload
      - perl-overloading
      - perl-parent
      - perl-podlators
      - perl-srpm-macros
      - perl-subs
      - perl-vars
      - pkgconf
      - pkgconf-m4
      - pkgconf-pkg-config
      - popt
      - publicsuffix-list-dafsa
      - python-pip-wheel
      - python-setuptools-wheel
      - python-srpm-macros
      - python-unversioned-command
      - python3
      - python3-libs
      - python3-pip
      - python3-setuptools
      - qrencode-libs
      - qt5-srpm-macros
      - rdma-core
      - readline
      - redhat-rpm-config
      - rpm
      - rpm-build
      - rpm-build-libs
      - rpm-libs
      - rust-srpm-macros
      - s390utils-base
      - s390utils-core
      - sed
      - setup
      - sg3_utils
      - sg3_utils-libs
      - shadow-utils
      - shared-mime-info
      - sqlite-libs
      - sysfsutils
      - systemd
      - systemd-libs
      - systemd-pam
      - systemd-rpm-macros
      - tar
      - trousers
      - trousers-lib
      - tzdata
      - unzip
      - util-linux
      - which
      - whois-nls
      - xkeyboard-config
      - xxhash-libs
      - xz
      - xz-libs
      - zip
      - zlib
      - zstd
    x86_64:
  source_packages:
    aarch64:
    ppc64le:
    s390x:
    x86_64:
  failed_buildroot:
    aarch64:
    ppc64le:
    s390x:
    x86_64:
