document: feedback-pipeline-workload
version: 1
data:
  name: CEE support tools
  description: Support tools used by customers and Support Delivery
  maintainer: sst_cee_supportability

  packages:
  - redhat-support-lib-python
  - redhat-support-tool
  - sos
  - support-tools-container

  labels:
- eln
