---
document:  feedback-pipeline-workload
version: 1
data:
    name: ELN Buildroot Workload
    description: The packages that are not part of ELN, but needed to build it.
    maintainer: tdawson
    labels:
        - eln-buildroot
    experimental:
        buildroot: True
    repositories:
        - repository-fedora-eln
    packages:
        - accountsservice-devel
        - adobe-mappings-cmap-devel
        - adobe-mappings-pdf-devel
        - adwaita-icon-theme-devel
        - amtk-devel
        - ant-apache-xalan2
        - ant-contrib
        - anthy-devel
        - ant-junit
        - antlr-tool
        - apache-commons-jxpath
        - apache-commons-logging-javadoc
        - apache-commons-net
        - apache-commons-parent
        - apr-devel
        - apr-util-devel
        - aqute-bnd
        - aspell-devel
        - aspell-en
        - assertj-core
        - assimp-devel
        - atf-tests
        - atkmm-devel
        - augeas-devel
        - autoconf-archive
        - autogen
        - autogen-libopts-devel
        - avahi-devel
        - avahi-glib-devel
        - avahi-gobject-devel
        - b43-tools
        - babl-devel
        - bcel
        - beakerlib
        - bind-devel
        - bind-lite-devel
        - bind-pkcs11-devel
        - bluez-libs-devel
        - brlapi-devel
        - bsdtar
        - btrfs-progs-devel
        - byaccj
        - cairomm-devel
        - cal10n
        - cglib
        - cheese-libs-devel
        - chrpath
        - cifs-utils-devel
        - clutter-devel
        - clutter-gst3-devel
        - clutter-gtk-devel
        - cmake
        - cmake-rpm-macros
        - cogl-devel
        - colord-devel
        - colord-gtk-devel
        - compat-guile18-devel
        - compat-lua
        - cppcheck
        - cppunit-devel
        - cracklib-devel
        - cryptsetup-devel
        - cscope
        - CUnit-devel
        - datefudge
        - dconf-devel
        - dejagnu
        - device-mapper-devel
        - device-mapper-event-devel
        - dleyna-core-devel
        - docbook5-style-xsl
        - docbook-utils
        - docbook-utils-pdf
        - dom4j
        - dotconf-devel
        - double-conversion-devel
        - drpm-devel
        - easymock
        - egl-wayland-devel
        - elinks
        - emacs
        - enchant2-devel
        - enchant-devel
        - espeak-ng-devel
        - evince-devel
        - evolution-devel
        - exec-maven-plugin
        - exempi-devel
        - exim
        - exiv2-devel
        - expect
        - f32-backgrounds-kde
        - fcode-utils
        - felix-gogo-runtime
        - felix-osgi-obr
        - felix-parent
        - felix-shell
        - fftw-devel
        - file-devel
        - flac-devel
        - flatpak-devel
        - flex-devel
        - fluidsynth-devel
        - fonts-rpm-macros
        - fonttools
        - fuse-devel
        - fusesource-pom
        - fwupd-devel
        - gamin-devel
        - gavl-devel
        - gc-devel
        - GConf2-devel
        - gdbm-devel
        - gdlmm-devel
        - gdm-devel
        - gdm-pam-extensions-devel
        - geoclue2-devel
        - geronimo-jaxrpc
        - geronimo-jms
        - geronimo-jpa
        - geronimo-parent-poms
        - geronimo-saaj
        - giflib-devel
        - gimp-devel
        - gjs-devel
        - glade-devel
        - glassfish-legal
        - glassfish-servlet-api
        - glew-devel
        - glib2-doc
        - glibc-langpack-am
        - glibc-langpack-ar
        - glibc-langpack-cs
        - glibc-langpack-de
        - glibc-langpack-fr
        - glibc-langpack-ja
        - glibc-langpack-km
        - glibc-langpack-ko
        - glibc-langpack-pt
        - glibc-locale-source
        - glibc-static
        - glibmm24-devel
        - glm-devel
        - gnome-autoar-devel
        - gnome-common
        - gnome-doc-utils
        - gnome-settings-daemon-devel
        - gobject-introspection-devel
        - go-compilers-golang-compiler
        - golang-github-cpuguy83-md2man
        - go-rpm-macros
        - gperf
        - gpgme-devel
        - graphene-devel
        - graphviz-devel
        - grilo-devel
        - groff
        - gsl-devel
        - gsm-devel
        - gspell-devel
        - gssdp-devel
        - gtest-devel
        - gtkmm30-devel
        - gtksourceview4-devel
        - gtkspell3-devel
        - gtk-vnc2-devel
        - guile22-devel
        - guile-devel
        - gupnp-av-devel
        - gupnp-devel
        - gupnp-dlna-devel
        - gupnp-igd-devel
        - hamcrest
        - help2man
        - hidapi-devel
        - hsqldb-lib
        - httpcomponents-project
        - httpd-devel
        - http-parser-devel
        - hunspell-cs
        - hunspell-de
        - hunspell-en
        - hunspell-es
        - hunspell-fr
        - hunspell-it
        - hunspell-ko
        - i3
        - ibus-devel
        - icon-naming-utils
        - ilmbase-devel
        - ima-evm-utils-devel
        - ImageMagick
        - ImageMagick-c++-devel
        - imlib2-devel
        - isns-utils-devel
        - jack-audio-connection-kit-devel
        - jakarta-oro
        - janino
        - jansson-devel
        - jasper-devel
        - javacc
        - javacc-maven-plugin
        - java_cup
        - javamail
        - javapackages-local
        - jaxen
        - jbig2dec-devel
        - jbigkit-devel
        - jboss-logmanager
        - jboss-parent
        - jdepend
        - jdom
        - jflex
        - jimtcl-devel
        - jitterentropy-devel
        - jsch
        - json-c-devel
        - junit5
        - kmod-devel
        - krb5-server
        - kyua
        - lcms2-devel
        - ldns-devel
        - liba52-devel
        - libao-devel
        - libappindicator-devel
        - libappindicator-gtk3-devel
        - libappstream-glib-devel
        - libarchive-devel
        - libargon2-devel
        - libassuan-devel
        - libburn-devel
        - libcbor-devel
        - libcdio-devel
        - libcgroup-devel
        - libcmocka-devel
        - libcollection-devel
        - libconfig-devel
        - libconfuse-devel
        - libcroco-devel
        - libdaemon-devel
        - libdbusmenu-gtk3-devel
        - libdhash-devel
        - libdmx-devel
        - libdvdread-devel
        - libell-devel
        - libevdev-devel
        - libev-devel
        - libevent-devel
        - libexif-devel
        - libfontenc-devel
        - libgdither-devel
        - libgee-devel
        - libgexiv2-devel
        - libgovirt-devel
        - libgs-devel
        - libgsf-devel
        - libgtop2-devel
        - libgudev-devel
        - libgusb-devel
        - libgxps-devel
        - libhangul-devel
        - libidn2-devel
        - libidn-devel
        - libijs-devel
        - libimobiledevice-devel
        - libini_config-devel
        - libinput-devel
        - libiptcdata-devel
        - libisofs-devel
        - libkkc-devel
        - libknet1-devel
        - libksba-devel
        - liblangtag-devel
        - libldb-devel
        - liblouis-devel
        - liblqr-1-devel
        - libmaxminddb-devel
        - libmbim-devel
        - libmemcached-devel
        - libmicrohttpd-devel
        - libmng-devel
        - libmnl-devel
        - libmodman-devel
        - libmodulemd1
        - libmodulemd-devel
        - libmpc-devel
        - libmpeg2-devel
        - libmspack-devel
        - libmusicbrainz5-devel
        - libndp-devel
        - libnetfilter_conntrack-devel
        - libnfnetlink-devel
        - libnfsidmap-devel
        - libnftnl-devel
        - libnghttp2-devel
        - libnice-devel
        - libnma-devel
        - libnozzle1-devel
        - libnsl2-devel
        - liboauth-devel
        - libogg-devel
        - libosinfo-devel
        - libotf-devel
        - libpaper-devel
        - libpath_utils-devel
        - libpcap-devel
        - libpciaccess-devel
        - libpeas-devel
        - libpinyin-devel
        - libpinyin-tools
        - libpipeline-devel
        - libplist-devel
        - libproxy-devel
        - libpwquality-devel
        - libqb-devel
        - libqmi-devel
        - LibRaw-devel
        - librevenge-devel
        - libsamplerate-devel
        - libsemanage-devel
        - libsemanage-static
        - libsepol-static
        - libsigc++20-devel
        - libsigsegv-devel
        - libslirp-devel
        - libsndfile-devel
        - libspectre-devel
        - libssh2-devel
        - libsss_autofs
        - libstemmer-devel
        - libsysfs-devel
        - libtalloc-devel
        - libtdb-devel
        - libtevent-devel
        - libtheora-devel
        - libtirpc-devel
        - libtool-ltdl-devel
        - libudisks2-devel
        - libunistring-devel
        - libusb-devel
        - libusbmuxd-devel
        - libutempter-devel
        - libv4l-devel
        - libvirt-glib-devel
        - libvncserver-devel
        - libvoikko-devel
        - libvorbis-devel
        - libwacom-devel
        - libwmf-devel
        - libwpd-devel
        - libwpe-devel
        - libwpg-devel
        - libwsman-devel
        - libXdmcp-devel
        - libxkbcommon-x11-devel
        - libxkbfile-devel
        - libxklavier-devel
        - libxmlb-devel
        - libXres-devel
        - libXxf86vm-devel
        - libyaml-devel
        - libzip-devel
        - linuxdoc-tools
        - lockdev-devel
        - log4j
        - lua-devel
        - lua-lunit
        - lvm2-devel
        - lynx
        - lzip
        - m17n-db-devel
        - m17n-db-extras
        - m17n-lib-devel
        - marisa-devel
        - maven-antrun-plugin
        - maven-assembly-plugin
        - maven-dependency-plugin
        - maven-hawtjni-plugin
        - maven-invoker-plugin
        - maven-local
        - maven-plugin-testing-harness
        - maven-resolver-transport-file
        - maven-shade-plugin
        - maven-source-plugin
        - maven-wagon-http-lightweight
        - mdds-devel
        - mecab-devel
        - mesa-libgbm-devel
        - meson
        - mobile-broadband-provider-info-devel
        - mockito
        - modello
        - ModemManager-glib-devel
        - mod_perl
        - mojo-parent
        - mozjs68-devel
        - mtdev-devel
        - mt-st
        - mtx
        - multilib-rpm-config
        - munge-maven-plugin
        - nautilus-devel
        - ncompress
        - neon-devel
        - netpbm-progs
        - NetworkManager-libnm-devel
        - ninja-build
        - nodejs-devel
        - npm
        - npth-devel
        - nss_wrapper
        - ntfs-3g-devel
        - objectweb-pom
        - ocaml
        - ocaml-calendar-devel
        - ocaml-csv-devel
        - ocaml-curses-devel
        - ocaml-extlib-devel
        - ocaml-fileutils-devel
        - ocaml-findlib-devel
        - ocaml-libvirt-devel
        - ocaml-ocamldoc
        - ocaml-xml-light-devel
        - oniguruma-devel
        - openal-soft-devel
        - openblas-devel
        - openchange-devel
        - OpenEXR-devel
        - openjpeg2-devel
        - openldap-servers
        - opensmtpd
        - ostree-devel
        - PackageKit-glib-devel
        - pakchois-devel
        - pam_wrapper
        - pandoc
        - pangomm-devel
        - paranamer
        - pcaudiolib-devel
        - pcsc-lite-devel
        - perl-Alien-Build
        - perl-Alien-Libxml2
        - perl-B-COW
        - perl-Capture-Tiny
        - perl-Class-XSAccessor
        - perl-Config-AutoConf
        - perl-CPAN-Changes
        - perl-Crypt-OpenSSL-Guess
        - perl-DateTime-Format-HTTP
        - perl-DateTime-Format-IBeat
        - perl-DateTime-Format-Mail
        - perl-Devel-CheckLib
        - perl-Devel-Cycle
        - perl-Devel-Hide
        - perl-Digest-CRC
        - perl-Digest-SHA1
        - perl-ExtUtils-HasCompiler
        - perl-ExtUtils-PkgConfig
        - perl-File-ShareDir-Install
        - perl-HTTP-Daemon
        - perl-Import-Into
        - perl-IO-stringy
        - perl-IPC-Run
        - perl-libintl-perl
        - perl-Module-Install
        - perl-Net-DNS-Resolver-Mock
        - perl-Net-DNS-Resolver-Programmable
        - perl-Net-DNS-SEC
        - perl-Net-IDN-Encode
        - perl-Net-LibIDN
        - perl-Net-LibIDN2
        - perl-Object-Deadly
        - perl-Parallel-ForkManager
        - perl-PAR-Dist
        - perl-Path-Tiny
        - perl-Perl-Destruct-Level
        - perl-Readonly
        - perl-Sub-Name
        - perl-Sub-Quote
        - perl-Taint-Runtime
        - perl-Term-Size-Any
        - perl-Test2-Plugin-NoWarnings
        - perl-Test2-Suite
        - perl-Test2-Tools-Explain
        - perl-Test-CPAN-Meta
        - perl-Test-CPAN-Meta-JSON
        - perl-Test-Exception
        - perl-Test-FailWarnings
        - perl-Test-Fatal
        - perl-Test-File-ShareDir
        - perl-Test-Inter
        - perl-Test-LeakTrace
        - perl-Test-Manifest
        - perl-Test-Memory-Cycle
        - perl-Test-MockModule
        - perl-Test-Needs
        - perl-Test-Output
        - perl-Test-Pod
        - perl-Test-Pod-Coverage
        - perl-Test-Regexp
        - perl-Test-Requires
        - perl-Test-RequiresInternet
        - perl-Test-Taint
        - perl-Test-Warn
        - perl-Test-Warnings
        - perl-Test-Without-Module
        - perl-Tie-IxHash
        - perl-Unicode-EastAsianWidth
        - perl-YAML-LibYAML
        - php-devel
        - pipewire0.2-devel
        - pipewire-devel
        - plexus-ant-factory
        - plexus-component-api
        - plexus-components-pom
        - policycoreutils-devel
        - polkit-gnome
        - poppler-cpp-devel
        - poppler-data-devel
        - poppler-devel
        - poppler-glib-devel
        - portaudio-devel
        - postgresql-server
        - potrace-devel
        - powermock-api-easymock
        - powermock-api-mockito
        - powermock-junit4
        - ppp-devel
        - psl-make-dafsa
        - psutils
        - python2-cairo-devel
        - python3-Cython
        - python3-fonttools
        - python3-libvoikko
        - python3-marisa
        - python3-pylint
        - python3-talloc-devel
        - qpdf-devel
        - qt5-devel
        - qt5-qtbase-doc
        - qt5-qtwayland-devel
        - qt-devel
        - quota-devel
        - raptor2-devel
        - rasqal-devel
        - rest-devel
        - rmt
        - rpcgen
        - rpm-ostree-devel
        - rsh
        - rtl-sdr-devel
        - rubygem-asciidoctor
        - rubygem-builder
        - rubygem-minitest
        - rubygem-minitest4
        - rubygem-ronn
        - rubygem-rspec
        - rubygem-rspec2
        - sbc-devel
        - sblim-cmpi-devel
        - sblim-indication_helper-devel
        - SDL2-devel
        - SDL_sound-devel
        - selinux-policy-devel
        - sendmail
        - sg3_utils-devel
        - sharutils
        - ShellCheck
        - slf4j-sources
        - snappy-devel
        - socket_wrapper
        - sombok-devel
        - speex-devel
        - speexdsp-devel
        - spice-gtk3-devel
        - taglib-devel
        - tclx-devel
        - tcsh
        - teamd-devel
        - tepl-devel
        - texinfo
        - totem-pl-parser-devel
        - tracker-devel
        - transfig
        - ttembed
        - ttfautohint
        - uchardet-devel
        - uid_wrapper
        - unbound-devel
        - unicode-emoji
        - upower-devel
        - urw-base35-fonts-devel
        - userspace-rcu-devel
        - vte291-devel
        - vulkan-loader-devel
        - wordnet
        - xcb-util-devel
        - xdg-desktop-portal-devel
        - xmlto
        - xmltoman
        - xmlto-tex
        - xorg-sgml-doctools
        - xorg-x11-server-devel
        - xorg-x11-server-Xvfb
        - xorg-x11-util-macros
        - xorg-x11-xtrans-devel
        - yajl-devel
        - yelp-xsl-devel
        - zchunk-devel
    arch_packages:
        aarch64:
            - efivar-devel
            - gnu-efi
            - infiniband-diags-devel
            - lame-devel
            - libfprint-devel
            - libmad-devel
            - libraw1394-devel
            - python3-libpamtest
        ppc64le:
            - infiniband-diags-devel
            - lame-devel
            - libfprint-devel
            - libmad-devel
            - libraw1394-devel
            - librtas-devel
            - libservicelog-devel
            - python3-libpamtest
        s390x:
        x86_64:
            - efivar-devel
            - gnu-efi
            - infiniband-diags-devel
            - lame-devel
            - libfprint-devel
            - libmad-devel
            - libraw1394-devel
            - libXfont2-devel
            - libXvMC-devel
            - mesa-libxatracker-devel
            - python3-libpamtest
