---
document:  feedback-pipeline-workload
version: 1
data:
    name: ELN Buildroot Workload
    description: The packages that are not part of ELN, but needed to build it.
    maintainer: tdawson
    labels:
        - eln-buildroot
    experimental:
        buildroot: True
    repositories:
        - repository-fedora-eln
    packages:
        - accountsservice-devel
        - adobe-mappings-cmap-devel
        - adobe-mappings-pdf-devel
        - adwaita-icon-theme-devel
        - amtk-devel
        - ant-apache-xalan2
        - ant-junit
        - apache-commons-logging-javadoc
        - apr-devel
        - apr-util-devel
        - aqute-bnd
        - aspell-devel
        - assimp-devel
        - atkmm-devel
        - augeas-devel
        - autogen
        - autogen-libopts-devel
        - avahi-devel
        - avahi-glib-devel
        - avahi-gobject-devel
        - babl-devel
        - bind-devel
        - bind-lite-devel
        - bind-pkcs11-devel
        - bluez-libs-devel
        - brlapi-devel
        - btrfs-progs-devel
        - cairomm-devel
        - cglib
        - cheese-libs-devel
        - cifs-utils-devel
        - clutter-devel
        - clutter-gst3-devel
        - clutter-gtk-devel
        - cmake
        - cmake-rpm-macros
        - cogl-devel
        - colord-devel
        - colord-gtk-devel
        - cracklib-devel
        - cryptsetup-devel
        - dbus-python-devel
        - dconf-devel
        - device-mapper-devel
        - device-mapper-event-devel
        - dleyna-core-devel
        - dotconf-devel
        - drpm-devel
        - easymock
        - emacs
        - enchant2-devel
        - enchant-devel
        - espeak-ng-devel
        - evince-devel
        - evolution-devel
        - exempi-devel
        - exiv2-devel
        - fftw-devel
        - file-devel
        - flac-devel
        - flatpak-devel
        - flex-devel
        - fonts-rpm-macros
        - fuse-devel
        - fwupd-devel
        - gavl-devel
        - gc-devel
        - GConf2-devel
        - gdbm-devel
        - gdm-devel
        - gdm-pam-extensions-devel
        - geoclue2-devel
        - ghostscript-core
        - giflib-devel
        - gimp-devel
        - gjs-devel
        - glib2-doc
        - glibc-langpack-am
        - glibc-langpack-cs
        - glibc-langpack-fr
        - glibc-langpack-ja
        - glibc-langpack-km
        - glibc-langpack-ko
        - glibc-langpack-pt
        - glibc-locale-source
        - glibc-static
        - glibmm24-devel
        - gnome-autoar-devel
        - gnome-settings-daemon-devel
        - gobject-introspection-devel
        - go-rpm-macros
        - gpgme-devel
        - graphene-devel
        - graphviz-devel
        - grilo-devel
        - groff
        - gsm-devel
        - gspell-devel
        - gssdp-devel
        - gtkmm30-devel
        - gtksourceview4-devel
        - gtk-vnc2-devel
        - guile22-devel
        - guile-devel
        - gupnp-av-devel
        - gupnp-devel
        - gupnp-dlna-devel
        - gupnp-igd-devel
        - hamcrest
        - httpd-devel
        - hunspell-en
        - ibus-devel
        - ilmbase-devel
        - ima-evm-utils-devel
        - ImageMagick
        - imlib2-devel
        - isns-utils-devel
        - jansson-devel
        - jasper-devel
        - javapackages-local
        - jbig2dec-devel
        - jbigkit-devel
        - jitterentropy-devel
        - json-c-devel
        - jvnet-parent
        - kmod-devel
        - lcms2-devel
        - ldns-devel
        - liba52-devel
        - libao-devel
        - libappstream-glib-devel
        - libargon2-devel
        - libassuan-devel
        - libburn-devel
        - libcbor-devel
        - libcdio-devel
        - libcgroup-devel
        - libcollection-devel
        - libconfig-devel
        - libcroco-devel
        - libdaemon-devel
        - libdhash-devel
        - libdmx-devel
        - libdvdread-devel
        - libedit-devel
        - libevdev-devel
        - libev-devel
        - libevent-devel
        - libexif-devel
        - libfontenc-devel
        - libgdither-devel
        - libgee-devel
        - libgexiv2-devel
        - libgovirt-devel
        - libgs-devel
        - libgsf-devel
        - libgtop2-devel
        - libgudev-devel
        - libgusb-devel
        - libgxps-devel
        - libhangul-devel
        - libidn2-devel
        - libidn-devel
        - libijs-devel
        - libimobiledevice-devel
        - libini_config-devel
        - libinput-devel
        - libiptcdata-devel
        - libisofs-devel
        - libkkc-devel
        - libksba-devel
        - liblangtag-devel
        - libldb-devel
        - liblouis-devel
        - liblqr-1-devel
        - libmaxminddb-devel
        - libmbim-devel
        - libmng-devel
        - libmnl-devel
        - libmodman-devel
        - libmodulemd1
        - libmpc-devel
        - libmpeg2-devel
        - libmspack-devel
        - libmusicbrainz5-devel
        - libndp-devel
        - libnetfilter_conntrack-devel
        - libnfnetlink-devel
        - libnfsidmap-devel
        - libnftnl-devel
        - libnghttp2-devel
        - libnice-devel
        - libnma-devel
        - libnsl2-devel
        - liboauth-devel
        - libogg-devel
        - libosinfo-devel
        - libpaper-devel
        - libpath_utils-devel
        - libpcap-devel
        - libpciaccess-devel
        - libpeas-devel
        - libpinyin-devel
        - libpinyin-tools
        - libpipeline-devel
        - libplist-devel
        - libproxy-devel
        - libpwquality-devel
        - libqb-devel
        - libqmi-devel
        - LibRaw-devel
        - librevenge-devel
        - libsamplerate-devel
        - libsemanage-devel
        - libsemanage-static
        - libsepol-static
        - libsigc++20-devel
        - libsigsegv-devel
        - libslirp-devel
        - libsndfile-devel
        - libspectre-devel
        - libssh2-devel
        - libsss_autofs
        - libstemmer-devel
        - libsysfs-devel
        - libtalloc-devel
        - libtdb-devel
        - libtevent-devel
        - libtheora-devel
        - libtirpc-devel
        - libtool-ltdl-devel
        - libudisks2-devel
        - libunistring-devel
        - libusb-devel
        - libusbmuxd-devel
        - libutempter-devel
        - libv4l-devel
        - libvirt-glib-devel
        - libvncserver-devel
        - libvorbis-devel
        - libwacom-devel
        - libwmf-devel
        - libwpd-devel
        - libwpe-devel
        - libwsman-devel
        - libXdmcp-devel
        - libxkbcommon-x11-devel
        - libxkbfile-devel
        - libxklavier-devel
        - libxmlb-devel
        - libXres-devel
        - libXxf86vm-devel
        - libyaml-devel
        - libzip-devel
        - llvm-devel
        - llvm-static
        - llvm-test
        - lockdev-devel
        - lua-devel
        - lvm2-devel
        - m17n-db-devel
        - m17n-db-extras
        - m17n-lib-devel
        - marisa-devel
        - maven-hawtjni-plugin
        - maven-local
        - mecab-devel
        - mesa-libgbm-devel
        - mobile-broadband-provider-info-devel
        - ModemManager-glib-devel
        - mozjs68-devel
        - mtdev-devel
        - nautilus-devel
        - neon-devel
        - netpbm-progs
        - NetworkManager-libnm-devel
        - npth-devel
        - ntfs-3g-devel
        - objenesis
        - oniguruma-devel
        - openblas-devel
        - openchange-devel
        - OpenEXR-devel
        - openjpeg2-devel
        - ostree-devel
        - PackageKit-glib-devel
        - pakchois-devel
        - pangomm-devel
        - pcaudiolib-devel
        - pcsc-lite-devel
        - perl-Digest-SHA1
        - perl-YAML-LibYAML
        - php-devel
        - pipewire0.2-devel
        - pipewire-devel
        - policycoreutils-devel
        - poppler-cpp-devel
        - poppler-data-devel
        - poppler-devel
        - poppler-glib-devel
        - postgresql-server
        - ppp-devel
        - psl-make-dafsa
        - pygobject2-devel
        - python2-cairo-devel
        - python3-gobject-devel
        - python3-marisa
        - python3-pip
        - python3-talloc-devel
        - qpdf-devel
        - qt-devel
        - quota-devel
        - raptor2-devel
        - rasqal-devel
        - rest-devel
        - sbc-devel
        - sblim-indication_helper-devel
        - SDL2-devel
        - selinux-policy-devel
        - sg3_utils-devel
        - slf4j-sources
        - snappy-devel
        - speex-devel
        - speexdsp-devel
        - spice-gtk3-devel
        - taglib-devel
        - teamd-devel
        - tepl-devel
        - texinfo
        - totem-pl-parser-devel
        - tracker-devel
        - uchardet-devel
        - unbound-devel
        - upower-devel
        - urw-base35-fonts-devel
        - userspace-rcu-devel
        - vte291-devel
        - vulkan-loader-devel
        - xcb-util-devel
        - xdg-desktop-portal-devel
        - xorg-x11-server-devel
        - xorg-x11-server-Xvfb
        - yajl-devel
        - yelp-xsl-devel
        - zchunk-devel
    arch_packages:
        aarch64:
            - efivar-devel
            - lame-devel
            - libfprint-devel
            - libmad-devel
            - libraw1394-devel
        ppc64le:
            - lame-devel
            - libfprint-devel
            - libmad-devel
            - libraw1394-devel
            - librtas-devel
        s390x:
        x86_64:
            - efivar-devel
            - lame-devel
            - libfprint-devel
            - libmad-devel
            - libraw1394-devel
            - libXfont2-devel
            - libXvMC-devel
            - mesa-libxatracker-devel
