---
document:  feedback-pipeline-workload
version: 1
data:
    name: Rawhide-based ELN Prototype Buildroot Workload
    description: This is a prototype buildroot resolved against Rawhide repositories to help us figure out what to rebuild in ELN. You probably want to see the eln-buildroot-workload.
    maintainer: tdawson
    labels:
        - prototype-eln-buildroot
    experimental:
        buildroot: True
    repositories:
        - repository-fedora-rawhide
    packages:
        - 
    arch_packages:
        aarch64:
        ppc64le:
        s390x:
        x86_64:
