---
document:  feedback-pipeline-workload
version: 1
data:
    name: Rawhide-based ELN Prototype Buildroot Workload
    description: This is a prototype buildroot resolved against Rawhide repositories to help us figure out what to rebuild in ELN. You probably want to see the eln-buildroot-workload.
    maintainer: tdawson
    labels:
        - prototype-eln-buildroot
    experimental:
        buildroot: True
    repositories:
        - repository-fedora-rawhide
    packages:
        - adobe-source-code-pro-fonts
        - augeas
        - cracklib-devel
        - deltarpm
        - docbook-style-dsssl
        - docbook-utils
        - doxygen
        - elfutils-debuginfod-client-devel
        - elinks
        - fonts-rpm-macros
        - fonts-rpm-templates
        - gnupg2-smime
        - gtk-doc
        - icu
        - ImageMagick
        - js-jquery
        - json-c-devel
        - libappstream-glib-devel
        - libarchive-devel
        - libcmocka
        - libcmocka-devel
        - libevent-devel
        - libproxy-devel
        - libreport-devel
        - libreport-gtk-devel
        - libreport-web-devel
        - libtomcrypt
        - libtommath
        - meson
        - ninja-build
        - nodejs-docs
        - nodejs-full-i18n
        - openjade
        - opensp
        - perl-SGMLSpm
        - python3-anytree
        - python3-beaker
        - python3-crypto
        - python3-devel
        - python3-imagesize
        - python3-parameterized
        - python3-paste
        - python3-pyOpenSSL
        - python3-ruamel-yaml
        - python3-ruamel-yaml-clib
        - python3-snowballstemmer
        - python3-sphinx
        - python3-sphinxcontrib-applehelp
        - python3-sphinxcontrib-devhelp
        - python3-sphinxcontrib-htmlhelp
        - python3-sphinxcontrib-jsmath
        - python3-sphinxcontrib-qthelp
        - python3-sphinxcontrib-serializinghtml
        - python3-sphinx-theme-alabaster
        - python3-tempita
        - python3-unbound
        - python-systemd-doc
        - satyr-devel
        - uchardet
        - web-assets-filesystem
        - xapian-core-libs
        - xmlrpc-c-c++
        - xmlrpc-c-client++
        - xmlrpc-c-devel
        - xmlto
    arch_packages:
        aarch64:
        ppc64le:
            - lm_sensors-devel
        s390x:
            - lm_sensors-devel
        x86_64:
