---
document: feedback-pipeline-repository
version: 1
data:
  name: Fedora ELN + Rawhide
  description: Fedora ELN + Fedora Rawhide repositories
  maintainer: asamalik
  source:
    # This is a combination of Fedora Rawhide and the ELN repository
    fedora_release: "33"
    additional_repository: https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/$basearch/os/
    architectures:
    - armv7hl
    - aarch64
    - ppc64le
    - s390x
    - x86_64
