---
document: feedback-pipeline-repository
version: 1
data:
  name: Fedora ELN (backed by rawhide)
  description: Fedora ELN with rawhide as a backup for missing packages
  maintainer: asamalik
  source:
    # This is a combination of Fedora Rawhide and the ELN repository
    fedora_release: rawhide
    additional_repository: https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/$basearch/os/
    architectures:
    - aarch64
    - ppc64le
    - s390x
    - x86_64
