document: feedback-pipeline-workload
version: 1
data:
  name: GTK 2 toolkit
  description: Software toolkit for developing applications
  maintainer: sst_desktop

  packages:
  - gtk2
  - gtk-doc

  labels:
  - eln
