document: feedback-pipeline-workload
version: 1
data:
  name: Qt Toolkit
  description: Software toolkit for developing applications
  maintainer: sst_desktop_applications

  packages:
  - adwaita-qt
  - qt5
  - qt5-doc
  - qt5-qtcanvas3d
  - qt5-qtserialbus
  - qt5-qttranslations
  - qgnomeplatform

  labels:
  - eln
