document: feedback-pipeline-workload
version: 1
data:
  name: Python runtime
  description: Python interpretter and packages to create virtual environments and pip-install packages from PyPI
  maintainer: sst_cs_apps

  packages:
  - python3
  - python3-libs
  - python3-pip
  - python3-setuptools
  - python-unversioned-command

  labels:
  - eln

  package_placeholders:
    python3-pip:
      description: We will build this without tests in RHEL 9
      buildrequires:
        - bash-completion
        - ca-certificates
        - python3-devel
        - python3-setuptools
        - python3-rpm-generators
        - python3-wheel
      requires:
        - /usr/bin/python3
        - ca-certificates
        - python(abi) = 3.9
      srpm: python-pip
    python-pip-wheel:
      description: We will build this without tests in RHEL 9
      buildrequires:
        - bash-completion
        - ca-certificates
        - python3-devel
        - python3-setuptools
        - python3-rpm-generators
        - python3-wheel
      requires:
        - ca-certificates
      srpm: python-pip
