document: feedback-pipeline-workload
version: 1
data:
  name: C Runtime
  description: The minimum required C development environment.
  maintainer: sst_platform_tools

  packages:
  # The minimum development environment is this:
  - gcc
  - binutils
  - glibc
  - glibc-common
  - glibc-devel
  - glibc-headers-s390
  - glibc-headers-x86_64
  # We support only the C/POSIX/C.UTF-8 locales.
  - glibc-minimal-langpack

  labels:
  - eln
