document: feedback-pipeline-workload
version: 1
data:
  name: USBGuard
  description: Enforcing USB security policy
  maintainer: sst_security_special

  packages:
  - usbguard
  - usbguard-notifier
  - usbguard-selinux

  labels:
  - eln
