document: feedback-pipeline-workload
version: 1
data:
  name: GNOME Desktop
  description: GNOME Desktop core packages
  maintainer: sst_desktop

  packages:
  - fprintd
  - fprintd-pam
  - freerdp
  - gdm
  - glib2
  - glib2-doc
  - glib2-fam
  - glib2-static
  - glib2-tests
  - gnome-backgrounds
  - gnome-backgrounds-extra
  - gnome-control-center
  - gnome-color-manager
  - gnome-common
  - gnome-devel-docs
  - gnome-online-miners
  - gnome-remote-desktop
  - gnome-session
  - gnome-shell
  - gnome-shell-extension-auto-move-windows
  - gnome-shell-extension-dash-to-dock
  - gnome-shell-extension-drive-menu
  - gnome-shell-extension-native-window-placement
  - gnome-shell-extension-screenshot-window-sizer
  - gnome-shell-extension-systemMonitor
  - gnome-shell-extension-windowsNavigator
  - gnome-shell-extension-workspace-indicator
  - gunome-shell-extension-user-theme
  - gnome-tweaks
  - polkit-gnome
  - tracker
  - xdg-user-dirs-gtk

  labels:
  - eln

  package_placeholders:
    redhat-logos:
      description: Red Hat-related icons and pictures
      requires:
        - coreutils
      buildrequires:
        - syslinux-perl
        - netpbm-progs
        - hardlink
    redhat-logos-httpd:
      description: Red Hat-related icons and pictures used by httpd
      requires: []
      buildrequires: []
    redhat-logos-ipa:
      description: Red Hat-related icons and pictures used by IPA
      requires: []
      buildrequires: []
    redhat-backgrounds:
      description: Red Hat-related desktop backgrounds
      requires: []
      buildrequires: []
