document: feedback-pipeline-workload
version: 1
data:
  name: Go Toolset
  description: Collection of packages providing the golang compiler toolchain.
  maintainer: sst_platform_tools

  packages:
  - golang
  - golang-bin
  - golang-docs
  - golang-misc
  - golang-race
  - golang-shared
  - golang-src
  - golang-tests
  - delve

  labels:
  - eln
