document: feedback-pipeline-workload
version: 1
data:
  name: SSH Client and Server
  description: SSH tools needed to access systems remotely
  maintainer: sst_platform_security

  packages:
  - openssh-clients
  - openssh-server
  - openssh

  labels:
  - eln
