document: feedback-pipeline-workload
version: 1
data:
  name: Nautilus
  description: Default file manager in Workstation
  maintainer: sst_desktop

  packages:
  - sushi
  - nautilus
  - nautilus-sendto
  - file-roller

  labels:
  - eln
