document: feedback-pipeline-workload
version: 1
data:
  name: Go Toolset
  description: Collection of packages providing the golang compiler toolchain.
  maintainer: sst_platform_tools

  packages:
  - golang
  - golang-bin
  - golang-docs
  - golang-misc
  - golang-race
  - golang-shared
  - golang-src
  - golang-tests
  - go-srpm-macros

  labels:
  - eln

  package_placeholders:
    delve:
      description: This package is not in Fedora (yet), but we want to see it here.
      requires: []
      buildrequires:
      - golang
      - git
      - lsof
    go-toolset:
      description: Meta-package for go-toolset
      requires:
        - golang
      buildrequires: []
