document: feedback-pipeline-workload
version: 1
data:
  name: kpatch
  description: Dynamic kernel patch manager
  maintainer: sst_kernel_ft

  packages: []

  labels:      # <-- Please leave
  - eln        #     this unchanged.

  package_placeholders:
    # kpatch is a RHEL-only package
    kpatch:
      srpm: kpatch
      description: Dynamic kernel patch manager
      requires: []
      buildrequires: []
