document: feedback-pipeline-workload
version: 1
data:
  name: perl:5.32 module
  description: Perl 5.32
  maintainer: sst_cs_stacks
  labels:
  - eln
  packages:
  - perl
  - perl-Archive-Tar
  - perl-Attribute-Handlers
  - perl-autodie
  - perl-AutoLoader
  - perl-AutoSplit
  - perl-autouse
  - perl-B
  - perl-base
  - perl-Benchmark
  - perl-bignum
  - perl-blib
  - perl-Carp
  - perl-Class-Struct
  - perl-Compress-Raw-Bzip2
  - perl-Compress-Raw-Zlib
  - perl-Config-Extensions
  - perl-Config-Perl-V
  - perl-constant
  - perl-CPAN
  - perl-CPAN-Meta
  - perl-CPAN-Meta-Requirements
  - perl-CPAN-Meta-YAML
  - perl-Data-Dumper
  - perl-DBM_Filter
  - perl-DB_File
  - perl-debugger
  - perl-deprecate
  - perl-devel
  - perl-Devel-Peek
  - perl-Devel-PPPort
  - perl-Devel-SelfStubber
  - perl-diagnostics
  - perl-Digest
  - perl-Digest-MD5
  - perl-Digest-SHA
  - perl-DirHandle
  - perl-doc
  - perl-Dumpvalue
  - perl-DynaLoader
  - perl-Encode
  - perl-Encode-devel
  - perl-encoding
  - perl-encoding-warnings
  - perl-English
  - perl-Env
  - perl-Errno
  - perl-experimental
  - perl-Exporter
  - perl-ExtUtils-CBuilder
  - perl-ExtUtils-Command
  - perl-ExtUtils-Constant
  - perl-ExtUtils-Embed
  - perl-ExtUtils-Install
  - perl-ExtUtils-MakeMaker
  - perl-ExtUtils-Manifest
  - perl-ExtUtils-Miniperl
  - perl-ExtUtils-MM-Utils
  - perl-ExtUtils-ParseXS
  - perl-Fcntl
  - perl-fields
  - perl-File-Basename
  - perl-File-Compare
  - perl-File-Copy
  - perl-File-DosGlob
  - perl-File-Fetch
  - perl-File-Find
  - perl-File-Path
  - perl-File-stat
  - perl-File-Temp
  - perl-FileCache
  - perl-FileHandle
  - perl-filetest
  - perl-Filter
  - perl-Filter-Simple
  - perl-FindBin
  - perl-GDBM_File
  - perl-generators
  - perl-Getopt-Long
  - perl-Getopt-Std
  - perl-Hash-Util
  - perl-Hash-Util-FieldHash
  - perl-HTTP-Tiny
  - perl-I18N-Collate
  - perl-I18N-Langinfo
  - perl-I18N-LangTags
  - perl-if
  - perl-interpreter
  - perl-IO
  - perl-IO-Compress
  - perl-IO-Socket-IP
  - perl-IO-Zlib
  - perl-IPC-Cmd
  - perl-IPC-Open3
  - perl-IPC-SysV
  - perl-JSON-PP
  - perl-less
  - perl-lib
  - perl-libnet
  - perl-libnetcfg
  - perl-libs
  - perl-locale
  - perl-Locale-Maketext
  - perl-Locale-Maketext-Simple
  - perl-macros
  - perl-Math-BigInt
  - perl-Math-BigInt-FastCalc
  - perl-Math-BigRat
  - perl-Math-Complex
  - perl-Memoize
  - perl-meta-notation
  - perl-MIME-Base64
  - perl-Module-CoreList
  - perl-Module-CoreList-tools
  - perl-Module-Load
  - perl-Module-Load-Conditional
  - perl-Module-Loaded
  - perl-Module-Metadata
  - perl-mro
  - perl-NDBM_File
  - perl-Net
  - perl-Net-Ping
  - perl-NEXT
  - perl-ODBM_File
  - perl-Opcode
  - perl-open
  - perl-overload
  - perl-overloading
  - perl-Params-Check
  - perl-parent
  - perl-PathTools
  - perl-Perl-OSType
  - perl-perlfaq
  - perl-PerlIO-via-QuotedPrint
  - perl-ph
  - perl-Pod-Checker
  - perl-Pod-Escapes
  - perl-Pod-Functions
  - perl-Pod-Html
  - perl-Pod-Perldoc
  - perl-Pod-Simple
  - perl-Pod-Usage
  - perl-podlators
  - perl-POSIX
  - perl-Safe
  - perl-Scalar-List-Utils
  - perl-Search-Dict
  - perl-SelectSaver
  - perl-SelfLoader
  - perl-sigtrap
  - perl-Socket
  - perl-sort
  - perl-Storable
  - perl-subs
  - perl-Symbol
  - perl-Sys-Hostname
  - perl-Sys-Syslog
  - perl-Term-ANSIColor
  - perl-Term-Cap
  - perl-Term-Complete
  - perl-Term-ReadLine
  - perl-Test
  - perl-Test-Harness
  - perl-Test-Simple
  - perl-Text-Abbrev
  - perl-Text-Balanced
  - perl-Text-ParseWords
  - perl-Text-Tabs+Wrap
  - perl-Thread
  - perl-Thread-Queue
  - perl-Thread-Semaphore
  - perl-threads
  - perl-threads-shared
  - perl-Tie
  - perl-Tie-File
  - perl-Tie-Memoize
  - perl-Tie-RefHash
  - perl-Time
  - perl-Time-HiRes
  - perl-Time-Local
  - perl-Time-Piece
  - perl-Unicode-Collate
  - perl-Unicode-Normalize
  - perl-Unicode-UCD
  - perl-User-pwent
  - perl-utils
  - perl-vars
  - perl-version
  - perl-vmsish
  modules_enable:
  - perl:5.32
