document: feedback-pipeline-workload
version: 1
data:
  name: HTTP Servers - Squid Caching Proxy
  description: Core Services Stacks - Squid
  maintainer: sst_cs_stacks

  packages:
  - squid

  labels:
  - eln
