document: feedback-pipeline-unwanted
version: 1
data:
  name: Desktop Applications - Blocked packages
  description: Desktop Applications - Packages which should not be in ELN
  maintainer: sst_desktop_applications
  unwanted_packages:
  # Was in RHEL only because of Google Chrome, not needed anymore as they use dbus api for tray icon
  - libappindicator
  - libdbusmenu
  - libindicator
  # Replaced by GNOME Connections
  - vinagre
  # buggy; glib improved to make dconf work on NFS
  - gamin
  # Replaced by GNOME Remove Desktop
  - vino
  # GNOME Shell has its own polkit dialog implementation
  # https://src.fedoraproject.org/rpms/gnome-shell/c/cd9369de85703b98ededeee30f9a421bbb7ebc30?branch=master
  - polkit-gnome
  # Old or deprecated or unwanted or unused stuff
  - qrencode
  - rarian
  - yajl
  - GConf2
  labels:
  - eln
