document: feedback-pipeline-workload
version: 1
data:
  name: System tracing
  description: A collection of common system tracing tools
  maintainer: sst_kernel_tps

  packages:
  - bcc
  - bpftrace
  - perf
  - strace
  - trace-cmd
  - kernelshark

  labels:
  - eln
