document: feedback-pipeline-workload
version: 1
data:
  name: Virtualization on RHEL - KVM Userspace
  description: Userspace agents and tools that enable virtualization capabilities on RHEL
  maintainer: sst_virtualization

  packages:
  - amtterm
  - augeas
  - dtc
  - fuse-sshfs
  - gtk-vnc2
  - hexedit
  - hivex
  - ipxe-roms-qemu
  - libguestfs
  - libiscsi
  - libnbd
  - libosinfo
  - libvirt
  - libvirt-dbus
  - libvirt-glib
  - mdevctl
  - meson
  - ninja-build
  - nbdkit
  - netcf
  - ocaml
  - ocaml-libvirt
  - osinfo-db
  - osinfo-db-tools
  - po4a
  - python-augeas
  - python3-libvirt
  - qemu-guest-agent
  - qemu-kvm
  - seabios
  - sgabios
  - supermin
  - vhostmd
  - virt-install
  - virt-top
  - virt-what

  labels:
  - eln

  arch_packages:
    x86_64:
    - edk2-ovmf
    - virt-v2v
    - virt-p2v
    - xorg-x11-drv-qxl
    ppc64le:
    - SLOF
    - xorg-x11-drv-qxl
    aarch64:
    - edk2-aarch64
    - xorg-x11-drv-qxl

    libguestfs-winsupport:
      description: Add support for Windows guests to virt-v2v and virt-p2v
      requires: []
      buildrequires:
        - mingw-gcc
        - mingw-binutils
        - mingw-filesystem
        - mingw-headers
        - mingw-crt
        - mingw-srvany
      limit_arches:
      - x86_64
