document: feedback-pipeline-workload
version: 1
data:
  name: HW tools
  description: Various tools related to a specific hardware
  maintainer: sst_cs_plumbers

  packages:
  - biosdevname
  - ledmon
  - numad
  - sgpio
  - libatasmart

  package_placeholders:
    prefixdevname:
      description: This package is rhel-only NIC naming tool
      buildrequires:
      - rust-toolset
      - git
      - systemd-devel

  labels:
  - eln
