document: feedback-pipeline-workload
version: 1
data:
  name: HTTP Servers - NGINX
  description: Core Services Stacks - NGINX
  maintainer: sst_cs_stacks

  packages:
  - nginx
  - nginx-all-modules

  modules_enable:
  - nginx:1.18
  
  labels:
  - eln
