document: feedback-pipeline-workload
version: 1
data:
  name: OpenSCAP OVAL Development support
  description: Utilities to make SCAP authoring and debugging an easier task.
  maintainer: sst_platform_security

  packages:
  - oval-graph

  labels:
  - eln
