document: feedback-pipeline-workload
version: 1
data:
  name: Stacks - miscellaneous packages
  description: Core Services Stacks - miscellaneous packages
  maintainer: sst_cs_stacks

  packages:
  - expat
  - expat-devel
  - whois
  - time
  - pcre2
  - pcre2-devel
  - pcre
  - pcre-devel
  - quota
  - quota-nld
  - quota-rpc
  - quota-doc
  - quota-nls
  - quota-warnquota
  - sscg

  labels:
  - eln
