document: feedback-pipeline-workload
version: 1
data:
  name: Dependencies from CS System management SST
  description: Dependency only packages from CS System management SST
  maintainer: sst_cs_system_management

  packages:
  - basesystem
  - cdparanoia-libs
  - cdparanoia-devel
  - cdparanoia
  - cdrdao
  - libusal-devel
  - libusal
  - genisoimage
  - wodim
  - icedax
  - ceres-solver
  - ceres-solver-devel
  - dvd+rw-tools
  - eigen3-devel
  - eigen3-doc
  - gflags
  - gflags-devel
  - glog-devel
  - glog
  - gpgme
  - gpgme-devel
  - qgpgme-devel
  - python3-gpg
  - gpgmepp
  - gpgmepp-devel
  - qgpgme
  - lensfun-devel
  - lensfun
  - leptonica
  - leptonica-devel
  - libburn
  - libburn-devel
  - libcdio-devel
  - libcdio
  - libdvdread
  - libdvdread-devel
  - libieee1284
  - libieee1284-devel
  - libisofs
  - libisofs-devel
  - libsmi
  - libsmi-devel
  - metis-devel
  - metis
  - mpfr-devel
  - mpfr
  - oniguruma
  - oniguruma-devel
  - sparsehash-devel
  - tesseract
  - tesseract-devel
  - tesseract-langpack-kat
  - tesseract-langpack-tam
  - tesseract-langpack-syr
  - tesseract-langpack-tir
  - tesseract-langpack-iku
  - tesseract-langpack-yid
  - tesseract-langpack-ben
  - tesseract-langpack-mkd
  - tesseract-langpack-ceb
  - tesseract-langpack-grc
  - tesseract-langpack-hat
  - tesseract-langpack-cym
  - tesseract-langpack-lit
  - tesseract-langpack-lat
  - tesseract-langpack-ron
  - tesseract-langpack-spa
  - tesseract-langpack-ori
  - tesseract-langpack-slk
  - tesseract-langpack-chr
  - tesseract-langpack-hun
  - tesseract-langpack-dan_frak
  - tesseract-langpack-ita
  - tesseract-langpack-deu
  - tesseract-langpack-san
  - tesseract-langpack-nep
  - tesseract-langpack-dzo
  - tesseract-langpack-aze
  - tesseract-langpack-bod
  - tesseract-langpack-hin
  - tesseract-langpack-bel
  - tesseract-langpack-khm
  - tesseract-langpack-swe
  - tesseract-langpack-ukr
  - tesseract-langpack-gle
  - tesseract-langpack-ces
  - tesseract-langpack-pan
  - tesseract-langpack-mal
  - tesseract-langpack-isl
  - tesseract-langpack-cat
  - tesseract-langpack-por
  - tesseract-langpack-tel
  - tesseract-langpack-heb
  - tesseract-langpack-eus
  - tesseract-langpack-slk_frak
  - tesseract-langpack-fin
  - tesseract-langpack-guj
  - tesseract-langpack-sqi
  - tesseract-langpack-nor
  - tesseract-langpack-afr
  - tesseract-langpack-mya
  - tesseract-langpack-fra
  - tesseract-langpack-epo
  - tesseract-langpack-tgl
  - tesseract-langpack-kor
  - tesseract-langpack-lao
  - tesseract-langpack-amh
  - tesseract-langpack-swa
  - tesseract-langpack-chi_tra
  - tesseract-langpack-kur
  - tesseract-langpack-ita_old
  - tesseract-langpack-tha
  - tesseract-langpack-pus
  - tesseract-langpack-uzb
  - tesseract-langpack-srp_latn
  - tesseract-langpack-vie
  - tesseract-langpack-lav
  - tesseract-langpack-spa_old
  - tesseract-langpack-tur
  - tesseract-langpack-ind
  - tesseract-langpack-frk
  - tesseract-langpack-ara
  - tesseract-langpack-frm
  - tesseract-langpack-aze_cyrl
  - tesseract-langpack-msa
  - tesseract-langpack-tgk
  - tesseract-langpack-equ
  - tesseract-langpack-mar
  - tesseract-langpack-fas
  - tesseract-langpack-est
  - tesseract-langpack-bos
  - tesseract-langpack-slv
  - tesseract-langpack-deu_frak
  - tesseract-langpack-urd
  - tesseract-langpack-hrv
  - tesseract-langpack-nld
  - tesseract-langpack-kir
  - tesseract-langpack-glg
  - tesseract-langpack-pol
  - tesseract-langpack-chi_sim
  - tesseract-langpack-mlt
  - tesseract-langpack-rus
  - tesseract-langpack-ell
  - tesseract-langpack-asm
  - tesseract-langpack-uig
  - tesseract-langpack-kaz
  - tesseract-langpack-kat_old
  - tesseract-langpack-uzb_cyrl
  - tesseract-langpack-enm
  - tesseract-langpack-srp
  - tesseract-langpack-dan
  - tesseract-langpack-kan
  - tesseract-langpack-sin
  - tesseract-langpack-jav
  - tesseract-langpack-jpn
  - tesseract-langpack-bul

  labels:
  - eln
