document: feedback-pipeline-unwanted
version: 1
data:
  name: LLVM Toolset Exclusion List
  description: LLVM sub-projects that should not be included.
  maintainer: sst_platform_tools

  unwanted_packages:
  - libcxx
  - libcxx-devel
  - libcxx-static
  - libcxxabi
  - libcxxabi-devel
  - libcxxabi-static

  labels:
  - eln
