document:  feedback-pipeline-workload
version: 1
data:
    name: kernel-rt devel/debug
    description: Kernel RT packages used for devel/debug
    maintainer: sst_kernel_rats
    packages: []
    labels:
        - eln
    arch_packages:
        x86_64:
            - kernel-rt-debuginfo-common-x86_64

    package_placeholders:
      kernel-rt-debuginfo:
        description: This package is not in Fedora (yet), but we want it here.
        requires:
          - bash
          - systemd-udev
          - coreutils
          - dracut
          - linux-firmware
          - systemd
        buildrequires:
          - kmod
          - patch
          - bash
          - coreutils
          - tar
          - git
          - which
          - bzip2
          - xz
          - findutils
          - gzip
          - m4
          - perl-interpreter
          - perl-Carp
          - perl-devel
          - perl-generators
          - make
          - diffutils
          - gawk
          - gcc
          - binutils
          - redhat-rpm-config
          - hmaccalc
          - python3-devel
          - net-tools
          - hostname
          - bc
          - bison
          - flex
          - elfutils-devel
          - dwarves
          - openssl
          - openssl-devel
          - rpm-build
          - elfutils

      kernel-rt-devel:
        description: This package is not in Fedora (yet), but we want it here.
        requires:
          - bash
          - systemd-udev
          - coreutils
          - dracut
          - linux-firmware
          - systemd
        buildrequires:
          - kmod
          - patch
          - bash
          - coreutils
          - tar
          - git
          - which
          - bzip2
          - xz
          - findutils
          - gzip
          - m4
          - perl-interpreter
          - perl-Carp
          - perl-devel
          - perl-generators
          - make
          - diffutils
          - gawk
          - gcc
          - binutils
          - redhat-rpm-config
          - hmaccalc
          - python3-devel
          - net-tools
          - hostname
          - bc
          - bison
          - flex
          - elfutils-devel
          - dwarves
          - openssl
          - openssl-devel
