document: feedback-pipeline-workload
version: 1
data:
  name: Stacks - miscellaneous packages
  description: Core Services Stacks - miscellaneous packages
  maintainer: sst_cs_stacks

  packages:
  - expat
  - whois
  - time
  - pcre2
  - pcre
  - quota
  - sscg

  labels:
  - eln
