document: feedback-pipeline-workload
version: 1
data:
  name: GNOME Boxes
  description: Default application to manager virtual machines in Workstation
  maintainer: sst_desktop_applications

  packages:
   - gnome-boxes

  labels:
  - eln
