document:  feedback-pipeline-workload
version: 1
data:
    name: kernel-rt base
    description: Base set of kernel-rt packages and tools to ship
    maintainer: sst_kernel_rats
    packages: []
    labels:
        - eln

    package_placeholders:
      kernel-rt:
        description: This package is not in Fedora (yet), but we want it here.
        requires:
          - bash
          - systemd-udev
          - coreutils
          - dracut
          - linux-firmware
          - systemd
        buildrequires:
          - kmod
          - patch
          - bash
          - coreutils
          - tar
          - git
          - which
          - bzip2
          - xz
          - findutils
          - gzip
          - m4
          - perl-interpreter
          - perl-Carp
          - perl-devel
          - perl-generators
          - make
          - diffutils
          - gawk
          - gcc
          - binutils
          - redhat-rpm-config
          - hmaccalc
          - python3-devel
          - net-tools
          - hostname
          - bc
          - bison
          - flex
          - elfutils-devel
          - dwarves
          - openssl
          - openssl-devel
        limit_arches:
          - x86_64

      kernel-rt-core:
        description: This package is not in Fedora (yet), but we want it here.
        requires:
          - bash
          - systemd-udev
          - coreutils
          - dracut
          - linux-firmware
          - systemd
        buildrequires:
          - kmod
          - patch
          - bash
          - coreutils
          - tar
          - git
          - which
          - bzip2
          - xz
          - findutils
          - gzip
          - m4
          - perl-interpreter
          - perl-Carp
          - perl-devel
          - perl-generators
          - make
          - diffutils
          - gawk
          - gcc
          - binutils
          - redhat-rpm-config
          - hmaccalc
          - python3-devel
          - net-tools
          - hostname
          - bc
          - bison
          - flex
          - elfutils-devel
          - dwarves
          - openssl
          - openssl-devel
        limit_arches:
          - x86_64

      kernel-rt-modules:
        description: This package is not in Fedora (yet), but we want it here.
        requires:
          - bash
          - systemd-udev
          - coreutils
          - dracut
          - linux-firmware
          - systemd
        buildrequires:
          - kmod
          - patch
          - bash
          - coreutils
          - tar
          - git
          - which
          - bzip2
          - xz
          - findutils
          - gzip
          - m4
          - perl-interpreter
          - perl-Carp
          - perl-devel
          - perl-generators
          - make
          - diffutils
          - gawk
          - gcc
          - binutils
          - redhat-rpm-config
          - hmaccalc
          - python3-devel
          - net-tools
          - hostname
          - bc
          - bison
          - flex
          - elfutils-devel
          - dwarves
          - openssl
          - openssl-devel
        limit_arches:
          - x86_64

      kernel-rt-modules-extra:
        description: This package is not in Fedora (yet), but we want it here.
        requires:
          - bash
          - systemd-udev
          - coreutils
          - dracut
          - linux-firmware
          - systemd
        buildrequires:
          - kmod
          - patch
          - bash
          - coreutils
          - tar
          - git
          - which
          - bzip2
          - xz
          - findutils
          - gzip
          - m4
          - perl-interpreter
          - perl-Carp
          - perl-devel
          - perl-generators
          - make
          - diffutils
          - gawk
          - gcc
          - binutils
          - redhat-rpm-config
          - hmaccalc
          - python3-devel
          - net-tools
          - hostname
          - bc
          - bison
          - flex
          - elfutils-devel
          - dwarves
          - openssl
          - openssl-devel
        limit_arches:
          - x86_64

      kernel-rt-kvm:
        description: This package is not in Fedora (yet), but we want it here.
        requires:
          - bash
          - systemd-udev
          - coreutils
          - dracut
          - linux-firmware
          - systemd
        buildrequires:
          - kmod
          - patch
          - bash
          - coreutils
          - tar
          - git
          - which
          - bzip2
          - xz
          - findutils
          - gzip
          - m4
          - perl-interpreter
          - perl-Carp
          - perl-devel
          - perl-generators
          - make
          - diffutils
          - gawk
          - gcc
          - binutils
          - redhat-rpm-config
          - hmaccalc
          - python3-devel
          - net-tools
          - hostname
          - bc
          - bison
          - flex
          - elfutils-devel
          - dwarves
          - openssl
          - openssl-devel
        limit_arches:
          - x86_64

      tuned-profiles-realtime:
        description: This package is not in Fedora (yet), but we want it here.
        requires:
          - bash
          - man

      tuned-profiles-nfv:
        description: This package is not in Fedora (yet), but we want it here.
        requires:
          - bash
          - man

      tuned-profiles-nfv-guest:
        description: This package is not in Fedora (yet), but we want it here.
        requires:
          - bash
          - man

      tuned-profiles-nfv-host:
        description: This package is not in Fedora (yet), but we want it here.
        requires:
          - bash
          - man

      tuned-profiles-nfv-host-bin:
        description: This package is not in Fedora (yet), but we want it here.
        buildrequires:
          - gcc
          - make
          - glibc
        limit_arches:
          - x86_64
