document: feedback-pipeline-workload
version: 1
data:
  name: Yelp
  description: Default help application in Workstation
  maintainer: sst_desktop_applications

  packages:
   - yelp

  labels:
  - eln
