document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted Packages -- Security Compliance
  description: Packages that Security Compliance won't distribute
  maintainer: sst_platform_security
  labels:
    - eln

  unwanted_packages:
    # dependency of oscap-anaconda-addon, because it's the only user, we do not
    # want to maintain it separately
    - python3-cpio

    # these pieces were part of Atomic Scan support in RHEL7, and we do not
    # expect to need them moving forward
    - openscap-daemon
    - openscap-container
