document: feedback-pipeline-workload
version: 1
data:
  name: NBDE
  description: Network-Bound Disc Encryption
  maintainer: sst_platform_security

  packages:
  - clevis
  - tang

  labels:
  - eln
