document: feedback-pipeline-workload
version: 1
data:
  name: 3D drivers
  description: Contains the user space APIs and 3D drivers for all GPUs supported in RHEL
  maintainer: sst_graphics_infrastructure

  packages:
    - mesa-libGL
    - mesa-dri-drivers
    - mesa-vulkan-drivers
    - mesa-libEGL
    - libglvnd
    - vulkan-validation-layers
    - vulkan-headers
    - vulkan-tools
    - vulkan-loader
    - mesa-demos
    - glslang
    - spirv-headers-devel

  labels:
    - eln
