document: feedback-pipeline-workload
version: 1
data:
  name: .NET
  description: .NET and .NET Core SDK, tools and runtime
  maintainer: sst_dotnet_java
  
  packages: []

  arch_packages:
    x86_64:
    - dotnet-sdk-3.1
    - dotnet-runtime-3.1
    - aspnetcore-runtime-3.1

  labels:
  - eln
