document: feedback-pipeline-unwanted
version: 1
data:
  name: Virtualization Exclusion List
  description: Virtualization packages not required in RHEL-9
  maintainer: sst_virtualization

  unwanted_packages:
  -

  labels:
  - eln
