document: feedback-pipeline-workload
version: 1
data:
  name: NBDE
  description: Network-Bound Disc Encryption
  maintainer: sst_security_special

  packages:
  - clevis
  - clevis-dracut
  - clevis-luks
  - clevis-systemd
  - clevis-udisks2
  - tang

  labels:
  - eln
