document: feedback-pipeline-workload
version: 1
data:
  name: SELinux devel
  description: A development packages
  maintainer: sst_security_selinux

  packages:
  - libsepol-devel
  - libselinux-devel
  - libsemanage-devel
  - python3-libselinux
  - python3-libsemanage
  - python3-policycoreutils

  labels:
  - eln
