document: feedback-pipeline-workload
version: 1
data:
  name: Virtualization on RHEL - KVM Userspace
  description: Userspace agents and tools that enable virtualization capabilities on RHEL
  maintainer: sst_virtualization

  packages:
  - amtterm
  - augeas
  - dtc
  - edk2
  - fuse-sshfs
  - gtk-vnc
  - hexedit
  - hivex
  - icoutils
  - ipxe-roms-qemu
  - libguestfs
  - libguestfs-winsupport
  - libiscsi
  - libnbd
  - libosinfo
  - libvirt
  - libvirt-dbus
  - libvirt-glib
  - libvirt-python
  - mdevctl
  - nbdkit
  - netcf
  - ocaml
  - ocaml-calendar
  - ocaml-cppo
  - ocaml-csv
  - ocaml-curses
  - ocaml-extlib
  - ocaml-fileutils
  - ocaml-findlib
  - ocaml-gettext
  - ocaml-labltk
  - ocaml-libvirt
  - ocaml-ocamlbuild
  - ocaml-srpm-macros
  - ocaml-xml-light
  - osinfo-db
  - osinfo-db-tools
  - phodav
  - po4a
  - python-augeas
  - qemu-guest-agent
  - qemu-kvm
  - rhevm-guest-agent
  - seabios
  - sgabios
  - spice-html5
  - supermin
  - vhostmd
  - virt-manager
  - virt-top
  - virt-what
  - xorg-x11-drv-qxl

  labels:
  - eln

  arch_packages:
    x86_64:
    - virt-v2v
    - virt-p2v
    ppc64le:
    - SLOF
