document: feedback-pipeline-workload
version: 1
data:
  name: OpenSCAP library
  description: OpenSCAP library and bindings
  maintainer: sst_platform_security

  packages:
  - openscap
  - openscap-devel
  - openscap-python3

  labels:
  - eln
