document: feedback-pipeline-workload
version: 1
data:
  name: Evolution
  description: Personal information management application for Workstation
  maintainer: sst_desktop_applications

  packages:
   - evolution
   - evolution-bogofilter
   - evolution-ews
   - evolution-mapi
   - evolution-spamassassin

  labels:
  - eln
