document: feedback-pipeline-workload
version: 1
data:
  name: Power Management
  description: Power Management related software
  maintainer: sst_cs_infra_services

  packages:
  - acpid 
  - powertop

  labels:
  - eln
