document: feedback-pipeline-workload
version: 1
data:
  name: Base Operating System packages
  description: Essential system packages
  maintainer: sst_cs_infra_services

  packages:
  - dosfstools
  - filesystem
  - grep
  - lm_sensors
  - lm_sensors-libs
  - lm_sensors-sensord
  - memtest86+
  - ncurses
  - ncurses-base
  - ncurses-term
  - setup

  labels:
  - eln
