document: feedback-pipeline-workload
version: 1
data:
  name: OpenSCAP utilities
  description: Wrappers and utilities to extend the usability of OpenSCAP scanner
  maintainer: sst_platform_security

  packages:
  - openscap-scanner
  - openscap-utils

  labels:
  - eln
