document: feedback-pipeline-workload
version: 1
data:
  name: GNOME Classic session
  description: GNOME Classic session
  maintainer: sst_desktop

  packages:
  - gnome-classic-session
  - gnome-menus
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-desktop-icons
  - gnome-shell-extension-horizontal-workspaces
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-window-list

  labels:
  - eln

  package_placeholders:
    # Only gnome-shell-extension-topicons-plus is available in Fedora
    gnome-shell-extension-top-icons:
      description: This GNOME Shell extension moves legacy tray icons into the top bar
      requires: []
      buildrequires: []
