document: feedback-pipeline-workload
version: 1
data:
  name: Fast Packet Processing Drivers, Libraries and Tools.
  description: >
    A set of libraries, drivers and tools required for configuration
    and fast packet processing.
  maintainer: sst_networking
  packages:
  - driverctl
  - dpdk
  - dpdk-tools
  - dpdk-devel
  - dpdk-doc

  labels:
  - eln
