document: feedback-pipeline-unwanted
version: 1
data:
  name: .NET and OpenJDK Unwanted Packages
  description: Packages that .NET and OpenJDK maintainers do not wish to maintain in RHEL 9
  maintainer: sst_dotnet_java
  labels:
  - eln

  unwanted_packages:
  # RHEL should only get explicitly versioned JDKs (e.g. java-17-openjdk), not the rolling java-latest-openjdk
  - java-latest-openjdk
  # Oracle dropped deployment tool support with JDK 10 (March 2018), we shouldn't support it for the RHEL 9 lifecycle
  - icedtea-web
