document: feedback-pipeline-workload
version: 1
data:
  name: edge packages
  description: Packages for edge usecases
  maintainer: jwboyer

  packages:
  - greenboot
  - greenboot-grub2
  - greenboot-reboot
  - greenboot-rpm-ostree-grub2
  - greenboot-status
  - ignition
  - ostree
  - rpm-ostree

  labels:
  - eln

