document: feedback-pipeline-workload
version: 1
data:
  name: edge packages
  description: Packages for edge usecases
  maintainer: sst_edge

  packages:
  - greenboot
  - greenboot-reboot
  - greenboot-rpm-ostree-grub2
  - greenboot-status
  - ignition
  - ostree
  - rpm-ostree

  arch_packages:
    x86_64:
    - greenboot-grub2
    ppc64le:
    - greenboot-grub2
    aarch64:
    - greenboot-grub2

  labels:
  - eln

