document: feedback-pipeline-workload
version: 1
data:
  name: os-prober
  description: Probes disks on the system for installed operating systems
  maintainer: sst_desktop

  packages:
  - os-prober

  labels:
  - eln
