document: feedback-pipeline-workload
version: 1
data:
  name: PHP scripting language
  description: Core Services Stacks - PHP
  maintainer: sst_cs_stacks

  packages:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-fpm
  - php-json
  - php-mbstring
  - php-pear
  - php-pecl-zip
  - php-process
  - php-xml
  - php-pear
  - php-pecl-apcu
  - php-pecl-apcu-devel
  - php-pecl-rrd
  - php-pecl-xdebug
  - php-pecl-zip

  labels:
  - eln
