document: feedback-pipeline-workload
version: 1
data:
  name: SCRUB
  description: Scrub writes patterns on files or disk devices to make retrieving the data more difficult.
  maintainer: sst_platform_security

  packages:
  - scrub

  labels:
  - eln
