document: feedback-pipeline-workload
version: 1
data:
  name: GNOME Terminal
  description: Default terminal application in Workstation
  maintainer: sst_desktop

  packages:
   - gnome-terminal

  labels:
  - eln
