document: feedback-pipeline-workload
version: 1
data:
  name: C++ Development Environment
  description: A minimal C++ development environment.
  maintainer: sst_platform_tools

  packages:
  # The minimum development environment is this:
  - gcc
  - gcc-c++
  - binutils
  - glibc
  - glibc-common
  - glibc-devel
  - libstdc++
  - libstdc++-devel
  - libgcc
  # Noarch header packages.
  - glibc-headers-s390
  - glibc-headers-x86
  # We support only the C/POSIX/C.UTF-8 locales.
  - glibc-minimal-langpack

  labels:
  - eln
