document: feedback-pipeline-workload
version: 1
data:
  name: rasdaemon
  description: Utility to receive RAS error tracings
  maintainer: sst_kernel_ft

  packages: []

  labels:      # <-- Please leave
  - eln        #     this unchanged.


  # (Only include the following section if you have arch-specific packages.)
  #   arch_packages:
  #       x86_64:                    # <-- Architecture
  #           - arch-specific-package1   # <-- The list of binary RPM packages
  #               - arch-specific-package1   #     goes here.
  #
  arch_packages:
      x86_64:
          - rasdaemon
          - rasdaemon-debuginfo
          - rasdaemon-debugsource
      aarch64:
          - rasdaemon
          - rasdaemon-debuginfo
          - rasdaemon-debugsource
      ppc64le:
          - rasdaemon
          - rasdaemon-debuginfo
          - rasdaemon-debugsource
