document: feedback-pipeline-workload
version: 1
data:
  name: .NET
  description: .NET and .NET Core SDK, tools and runtime
  maintainer: sst_dotnet_java
  
  packages:
  - dotnet-sdk-3.1
  - dotnet-runtime-3.1
  - aspnetcore-runtime-3.1

  package_placeholders:
    dotnet-sdk-6.0:
      description: .NET 6.0 doesn't exist, yet, but it's being planned for release in Nov 2021.
      requires: []        # same dependencies as dotnet-sdk-3.1
      buildrequires: []   # same dependencies as dotnet-sdk-3.1

  labels:
  - eln
