document: feedback-pipeline-workload
version: 1
data:
  name: OpenSCAP scanner
  description: OpenSCAP scanner, an open source SCAP scanning utility
  maintainer: sst_platform_security

  packages:
  - openscap
  - openscap-scanner

  labels:
  - eln
