document: feedback-pipeline-workload
version: 1
data:
  name: Performance Tools
  description: Performance Tools and Components
  maintainer: sst_platform_tools

  packages:
  - dyninst
  - dyninst-devel
  - dyninst-doc
  - dyninst-testsuite
  - elfutils
  - elfutils-debuginfod
  - elfutils-debuginfod-client
  - elfutils-debuginfod-client-devel
  - elfutils-default-yama-scope
  - elfutils-devel
  - elfutils-libelf
  - elfutils-libelf-devel
  - elfutils-libs
  - libpfm
  - libpfm-devel
  - papi
  - papi-devel
  - papi-libs
  - papi-testsuite
  - systemtap
  - systemtap-client
  - systemtap-devel
  - systemtap-exporter
  - systemtap-runtime
  - systemtap-runtime-java
  - systemtap-runtime-python3
  - systemtap-runtime-virtguest
  - systemtap-runtime-virthost
  - systemtap-sdt-devel
  - systemtap-server
  - systemtap-testsuite
  - valgrind
  - valgrind-devel

  labels:
  - eln
