document: feedback-pipeline-workload
version: 1
data:
  name: OpenSCAP SCE
  description: OpenSCAP Script Check Engine addon.
  maintainer: sst_platform_security

  packages:
  - openscap
  - openscap-engine-sce

  labels:
  - eln
