document: feedback-pipeline-unwanted
version: 1
data:
  name: Platform Tools Unwanted Packages
  description: Packages that Platform Tool maintains in RHEL 8 but won't in RHEL 9
  maintainer: Dodji Seketeli, Nick Clifton
  labels:
  - eln

  unwanted_packages:
  - cloog
  - cloog-devel
  - cppcheck
  - cppcheck-gui
  - cppcheck-htmlreport
  - cppunit
  - cppunit-devel
  - cppunit-doc
  - tinyxml2
  - tinyxml2-devel
  - dpkg
  - dpkg-devel
  - dselect
  - nasm
  - nasm-rdoff
  - yasm
  - yasm-devel
