document: feedback-pipeline-workload
version: 1
data:
  name: GNOME Classic session
  description: GNOME Classic session
  maintainer: sst_desktop

  packages:
  - gnome-classic-session
  - gnome-classic-session
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-desktop-icons
  - gnome-shell-extension-horizontal-workspaces
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-top-icons
  - gnome-shell-extension-window-list

  labels:
  - eln
