document: feedback-pipeline-workload
version: 1
data:
  name: GNOME Desktop
  description: GNOME Desktop core packages
  maintainer: sst_desktop

  packages:
   - fprintd
   - gdm
   - gnome-backgrounds
   - gnome-control-center
   - gnome-color-manager
   - gnome-common
   - gnome-devel-docs
   - gnome-online-miners
   - gnome-remote-desktop
   - gnome-session
   - gnome-shell
   - gnome-tweaks
   - polkit-gnome
   - tracker
   - xdg-user-dirs-gtk

  labels:
  - eln
