document: feedback-pipeline-workload
version: 1
data:
  name: AUDIT
  description: The user space utilities for storing and searching of audit events.
  maintainer: sst_security_special

  packages:
  - audit
  - audit-libs
  - audit-devel
  - audit-libs-devel
  - python3-audit
  - audispd-plugins
  - audispd-plugins-zos

  labels:
  - eln
