document: feedback-pipeline-workload
version: 1
data:
  maintainer: sst_platform_security
  name: Unwanted security/cryptography packages
  description: Unwanted packages implementing cryptogtraphy
  
  # Simo Sorce: The packages are unwanted either because they are
  # bad cryptography implementation, unmaintained, or simply not
  # certifiable or redundant (same functionality already present
  # in multiple crypto packages already and we do not want to add
  # more).
  # More info in the original PR 15

  packages:
  - libsodium
  - libssh2
  - libtomcrypt
  - python2-pycryptodomex
  - python3-ecdsa
  - python3-pycryptodomex
  
  labels:
  - eln
