document: feedback-pipeline-workload
version: 1
data:
  name: I2C tools
  description: Communication with I2C devices. This may include reading data from sensors, communication with EEPROMS, uses in robotics, embedded, IoT devices, industrial automation.
  maintainer: sst_cs_infra_services

  packages:
  - i2c-tools
  - i2c-tools-eepromer
  - i2c-tools-perl
  - libi2c

  labels:
  - eln
