document: feedback-pipeline-workload
version: 1
data:
  name: Rust Toolset
  description: Collection of packages providing the rust compiler toolchain.
  maintainer: sst_platform_tools

  packages:
  - rust
  - cargo
  - clippy
  - rls
  - rust-analysis
  - rust-doc
  - rust-std-static
  - rustfmt

  labels:
  - eln
