document: feedback-pipeline-workload
version: 1
data:
  name: C Development Environment
  description: A minimal C development environment.
  maintainer: sst_platform_tools

  packages:
  # The minimum development environment is this:
  - gcc
  - binutils
  - glibc
  - glibc-common
  - glibc-devel
  # Noarch header packages.
  - glibc-headers-x86
  - glibc-headers-s390
  # We support only the C/POSIX/C.UTF-8 locales.
  - glibc-minimal-langpack

  labels:
  - eln
