document: feedback-pipeline-workload
version: 1
data:
  name: Openstack
  description: Package dependencies needed by Openstack
  maintainer: sst_openstack

  packages:
  - augeas
  - autogen
  - babel
  - babeltrace
  - celt051
  - cloud-init
  - cloud-utils-growpart
  - clufter
  - corosync
  - dbxtool
  - dhcp-client
  - dpdk
  - driverctl
  - dwz
  - emacs
  - efivar
  - fence-agents
  - fence-virt
  - libkcapi-fipscheck
  - gperftools
  - genisoimage
  - git
  - haproxy
  - hivex
  - hostname
  - icu
  - ipa-client
  - ipmitool
  - ipxe-bootimgs
  - ipxe-roms
  - ipxe-roms-qemu
  - isns-utils
  - jasper
  - jbigkit
  - keepalived
  - leveldb
  - libknet1
  - libnozzle1
  - libknet1-plugins-all
  - libcacard
  - libcgroup
  - libcroco
  - liberation-fonts
  - libev
  - libguestfs
  - libiscsi
  - librabbitmq
  - libreswan
  - libwayland-client
  - libwayland-egl
  - libwayland-server
  - libbasicobjects
  - libcollection
  - libdhash
  - libini_config
  - libpath_utils
  - libref_array
  - lsscsi
  - mesa-filesystem
  - mesa-dri-drivers
  - mozjs78
  - netcf
  - nvme-cli
  - nvmetcli
  - oathtool
  - OpenIPMI
  - openvswitch
  - ovn
  - pacemaker
  - pcs
  - podman
  - pskctool
  - python3-libvirt
  - python3-mod_wsgi
  - qemu-kvm
  - qt5
  - redis
  - resource-agents
  - ruby
  - runc
  - samba
  - python3-scipy
  - scrub
  - setools
  - sg3_utils
  - skopeo
  - socat
  - spice-server
  - sshpass
  - sssd
  - stunnel
  - supermin
  - sysfsutils
  - targetcli
  - tftp
  - unbound
  - usbredir
  - volume_key
  - yajl
  - zip

  labels:
  - eln
