document: feedback-pipeline-workload
version: 1
data:
  name: C Runtime
  description: C development environment.
  maintainer: sst_platform_tools

  packages:
  # The minimum development environment is this:
  - gcc
  - binutils
  - glibc
  - glibc-common
  - glibc-devel
  - glibc-headers-s390
  - glibc-headers-x86_64
  # Full development includes additional packages:
  - glibc-utils
  - glibc-static
  - glibc-nss-devel
  # Support all locales.
  - glibc-all-lancpacks

  labels:
  - eln
