document: feedback-pipeline-workload
version: 1
data:
  name: Package Manager
  description: Recommended installation of package manager and plugins
  maintainer: sst_cs_software_management

  packages:
  - dnf
  - dnf-automatic
  - dnf-plugins-core
  - dnf-utils
  - python3-dnf-plugin-post-transaction-actions
  - python3-dnf-plugin-versionlock
  - rpm
  - rpm-plugin-selinux
  - rpm-plugin-systemd-inhibit

  labels:
  - eln
