document: feedback-pipeline-workload
version: 1
data:
  name: Application Whitelisting
  description: Packages providing application whitelisting functionality
  maintainer: sst_platform_security

  packages:
  - fapolicyd
  - fapolicyd-selinux

  labels:
  - eln
