document: feedback-pipeline-workload
version: 1
data:
  name: Kernel ABI support
  description: Tools necessary to support Kernel ABI.
  maintainer: sst_kernel_tps
  packages:
  - ksc
  - kabi-dw
  labels:
  - eln
