document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted ELN packages
  description: Various unwanted packages. See comments in the config for more detail.
  maintainer: bakery
  labels:
  - eln

  ###  Unwanted packages in ELN  ###
  #
  # Before using this list, please consider your own exclusion list
  # such as "sst_cs_software_management-unwanted.yaml" as an example.
  # This helps track ownership better, as you can set the maintainer
  # field to represent you or your team.
  #
  # When adding a package to the following list, please include your
  # name and the reason of why are you listing it.

  unwanted_packages:
  
  # Josh Boyer: Drop R from ELN to see what the fallout is.
  - R
  
  # Enterprise doesn't support btrfs
  - btrfs-progs
  - btrfs-progs-devel

  # Josh Boyer: Mono hasn't been carried in RHEL and there are
  # no plans to add it. Exclude it from ELN for now.
  - mono-core
  - mono-devel
  - monodoc
  - monodoc-devel
  
  # Troy Dawson
  - xen
  - xen-devel
  - xen-hypervisor
  - xen-libs
  - xen-licenses
  - xen-ocaml
  - xen-ocaml-devel
  - xen-runtime
  - xen-doc

  # Simo Sorce: The packages added in this PR are unwanted either
  # because they are bad cryptography implementation, unmaintained,
  # or simply not certifiable or redundant (same functionality
  # already present in multiple crypto packages already and we do
  # not want to add more).
  # More info in PR 15
  - libsodium
  - libssh2
  - libtomcrypt
  - python2-pycryptodomex
  - python3-ecdsa
  - python3-pycryptodomex

  # Vít Ondruch: rubygems is subpackage of ruby package and therefore
  # the independent version is not needed. rubypick is not needed and
  # there is %bcond_without to disable it
  - rubygems
  - rubypick

  # Radek Vykydal:
  # system-config-kickstart has been deprecated upstream, it has not
  # been ported to Python 3, and shouldn't have been included in RHEL 8.
  - system-config-kickstart

  # Vendula Poncova: python3-pydbus has been replaced by python3-dasbus
  - python3-pydbus

  # Dalibor Pospisil:
  # beakerlib was just a build dependency of chkconfig
  # beakerlib must not be present in the customer facing compose / repos
  # it might be part of buildroot only if really needed
  - beakerlib

  # Vendula Poncova: python3-nose-testconfig and python3-rpmfluff were
  # pulled in as test dependencies of anaconda, they shouldn't be needed
  - python3-nose-testconfig
  - python3-rpmfluff
