---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Rawhide-based ELN Prototype
  description: This is a prototype resolved against Rawhide repositories to help us figure out what to rebuild in ELN. You probably want to see the 'ELN Package Set' view.
  maintainer: bakery
  labels:
  - eln
  repository: repository-fedora-rawhide
  

  ###  Unwanted packages in ELN  ###
  #
  # The list has moved to the "view-eln-and-buildroot.yaml" file,
  # because that way we can have just one file included into all the
  # various ELN views.
  #
  # So please use "view-eln-and-buildroot.yaml" instead.