---
document: feedback-pipeline-compose-view
version: 1
data:
  name: ELN Package Set
  description: You can think about it as Enterprise Linux Next. More info https://fedoraproject.org/wiki/ELN
  maintainer: bakery
  labels:
  - eln
  repository: repository-fedora-eln
  

  ###  Unwanted packages in ELN  ###
  #
  # This file lists CONFIRMED unwanted packages in ELN.
  # 
  # To propose a new unwanted package, use the "exclusion.yml" config from: https://github.com/minimization/content-resolver/blob/master/config_specs/exclusion.yaml
  
  # Packages to be flagged as unwanted
  #unwanted_packages:

  # asamalik: confirming unwanted proposals
  # that are not required at the same time
  - clutter
  - clutter-gst3
  - clutter-gtk
  - cogl
  - drpm
  - ebtables-legacy
  - ed
  - elinks
  - fakeroot
  - fxload
  - gamin
  - glusterfs-cli
  - glusterfs-client-xlators
  - gssdp
  - gupnp
  - gupnp-igd
  - infinipath-psm
  - jsoncpp
  - ldns
  - libdbusmenu
  - libdbusmenu-gtk3
  - libdv
  - libgfapi0
  - libgfrpc0
  - libglusterd0
  - libglusterfs0
  - libiec61883
  - libimobiledevice
  - libmcpp
  - libnice
  - libplist
  - libpsm2
  - libradospp-devel
  - librhsm
  - libsamplerate
  - libtar
  - libunwind
  - libusbmuxd
  - libuv
  - lua
  - lua-posix
  - mailx
  - mcpp
  - ncurses-compat-libs
  - perl-Business-ISBN
  - perl-Text-CSV
  - python2.7
  - python3-cpio
  - python3-hawkey
  - python3-mock
  - python3-pydbus
  - rarian
  - redhat-lsb-core
  - redhat-lsb-submod-security
  - redhat-menus
  - rhash
  - rtkit
  - vorbis-tools
  - xorg-x11-drv-ati
  - xorg-x11-drv-intel
  - xorg-x11-drv-nouveau
  - xorg-x11-drv-qxl
  - xorg-x11-drv-vesa

  # Packages to be flagged as unwanted  on specific architectures
  #unwanted_arch_packages:
  #  x86_64:
  #  - arch-specific-package
  #  aarch64:
  #  - another-one

  # SRPMs (components) to be flagged as unwanted
  unwanted_source_packages:
  
  # jwboyer:
  - ImageMagick
  - bodhi
  - btrfs-progs
  - clufter
  - fedora-packager
  - fedpkg
  - koji
  - libsodium
  - libssh2
  - mercurial
  - mono
  - nagios-plugins
  - pungi
  - reiserfs-utils
  - spice
  - spice-gtk3
  - spice-html5
  - spice-vdagent
  - tomcat
  - xen
