---
document: feedback-pipeline-compose-view
version: 1
data:
  name: ELN Package Set
  description: You can think about it as Enterprise Linux Next. More info https://fedoraproject.org/wiki/ELN
  maintainer: bakery
  labels:
  - eln
  repository: repository-fedora-eln
  

  ###  Unwanted packages in ELN  ###
  #
  # The list has moved to the "view-eln-and-buildroot.yaml" file,
  # because that way we can have just one file included into all the
  # various ELN views.
  #
  # So please use "view-eln-and-buildroot.yaml" instead.